name: Level 1 Practice
on: workflow_dispatch
jobs:
   first-job:
     runs-on: ubuntu-latest

     steps:
        - name: checkout repository 
          uses: actions/checkout@v4
        - name: who is running the this?
          run: whoami
        - name: current working directory 
          run: pwd 
        - name: List files in repository 
          run: ls -la 
        - name: Number of files 
          run: find . -type f | wc -l
        - name: show OS details 
          run: uname -a 

          
